CREATE TABLE IF NOT EXISTS user1 (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS car1 (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    immatriculation VARCHAR(255) NOT NULL,
    marque VARCHAR(255) NOT NULL,
    modele VARCHAR(255) NOT NULL,
    etat VARCHAR(50)

);
