DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE car (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    marque VARCHAR(255) NOT NULL,
    modele VARCHAR(255) NOT NULL,
    statut VARCHAR(50),
    conducteur_id BIGINT,
    FOREIGN KEY (conducteur_id) REFERENCES app_user(id) ON DELETE SET NULL
);
